"""initial_baseline

Revision ID: dd688f5c7744
Revises: 
Create Date: 2026-07-01 07:38:58.475764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd688f5c7744'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_order_id'), 'documents', ['order_id'], unique=False)
    op.create_index(op.f('ix_documents_step_id'), 'documents', ['step_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_priority'), 'orders', ['priority'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_process_flows_created_at'), 'process_flows', ['created_at'], unique=False)
    op.create_index(op.f('ix_process_flows_order_id'), 'process_flows', ['order_id'], unique=False)
    op.create_index(op.f('ix_process_steps_flow_id'), 'process_steps', ['flow_id'], unique=False)
    op.create_index(op.f('ix_process_steps_status'), 'process_steps', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_process_steps_status'), table_name='process_steps')
    op.drop_index(op.f('ix_process_steps_flow_id'), table_name='process_steps')
    op.drop_index(op.f('ix_process_flows_order_id'), table_name='process_flows')
    op.drop_index(op.f('ix_process_flows_created_at'), table_name='process_flows')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_priority'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_documents_step_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_order_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    # ### end Alembic commands ###
